### ISSUE TITLE
Could you include an example?

### ISSUE THREAD

**Issue by TerryCavanagh** [djcsdy/kong.hx#1]
The Kongregate documentation is in AS3, leading to some unnecessary headaches in figuring this out!

**Comment by djcsdy** [comment]
Hi Terry,

Sorry about that. Thanks for your improvements!

I merged your changes. I also tried to make some of the wording in the README a bit clearer, and added some more examples.

I hope this makes things better, let me know if you think otherwise :-).

Dan.

**Comment by TerryCavanagh** [comment]
Great!

(I found this via google, and only realised who wrote this after I posted the pull request earlier, haha)
